version: '2'
services:
  api:
    build: ./
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    environment:
      RH_USERS_HOST: 0.0.0.0
      DB_HOST: postgres
    command: /bin/sh -c "npm run db:init && npm run db:migrate && npm run db:seed && npm run start:dev"
    links:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA : /var/lib/postgresql/data/pgdata
    volumes:
      - psqlvolumes:/var/lib/postgresql/data/pgdata

volumes:
  psqlvolumes:
    driver: local